run:
  timeout: 5m
  skip-files:
    - '(.+)_test\.go'

linters:
  disable-all: false
  disable:
    - gochecknoglobals
    - nlreturn
    - gomnd
    - nakedret
    - nolintlint
    - godot
    - varnamelen
    - nonamedreturns
  presets:
    - bugs
    - unused
    - style
  fast: false
