---
version: '2'

services:
  db:
    image: mariadb:10.2
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: onlyforadmin
      MYSQL_DATABASE: icinga2
      MYSQL_USER: icinga2
      MYSQL_PASSWORD: rosebud
    ports:
      - 3306:3306

  icinga2:
    image: lazyfrosch/icinga2
    depends_on:
      - db
    environment:
      ICINGA_NODENAME: icinga2.localdomain
      ICINGA_CA_ENABLE: 'true'
      ICINGA_CA_TICKET_SALT: yoloops
      ICINGA_API_USER_root: icinga
      ICINGA_IDO_ENABLE: 'true'
      ICINGA_IDO_HOST: db
      ICINGA_IDO_NAME: icinga2
      ICINGA_IDO_USERNAME: icinga2
      ICINGA_IDO_PASSWORD: rosebud
      ICINGA_IDO_INSTALL: 'true'
    networks:
      default:
        aliases:
          - icinga2.localdomain
    ports:
      - 5665:5665
    volumes:
      - icinga2_data:/var/lib/icinga2
      - icinga2_log:/var/log/icinga2

volumes:
  db_data:
  icinga2_data:
  icinga2_log:
